### ISSUE TITLE
Some tweaks on the introduction article

### ISSUE THREAD

**Issue by valo** [santiment/articles#2]
* I think here we should attribute coin metrics for the UTXO RV we compare to: https://github.com/santiment/articles/blob/master/transaction-stack-series-part-1/article.md#the-stack-coin-age-model

* The last paragraph of https://github.com/santiment/articles/blob/master/transaction-stack-series-part-1/article.md#account-based-blockchains is a bit hard for me follow. May be Dino can take a look and try to improve it

**Comment by tzanko-matev** [comment]
I changed the article to reflect those issues
